import { withTheme } from "vitepress-daisyui-theme/config";
import ggGrammar from "./gg.tmLanguage.json";
import { ggDiagramPlugin } from "./plugins/gg-diagram";

/**
 * Three-entry structure:
 *   - /         Language-select landing (neutral; picks /en/ or /ja/)
 *   - /en/…     English docs
 *   - /ja/…     Japanese docs
 *
 * VitePress requires a `root` locale. We use it to host ONLY the top-level
 * language picker at `/index.md`; the English docs live entirely under
 * `/en/*`, matching the `/ja/*` shape.
 */
export default withTheme({
  title: "Gridgram",
  description: "Diagrams for the AI era. A plain-text DSL that humans, CLIs, and LLMs all author fluently, with byte-deterministic SVG output.",
  cleanUrls: true,
  lastUpdated: true,
  // Phase 1: skeleton pages aren't all written yet — relax until content lands.
  ignoreDeadLinks: true,

  // `favicon.svg` is generated by `scripts/pick-monthly-logo.ts` from
  // `docs/public/icons/logo-NN.svg` (one of 12 variants, picked by the
  // current month). SVG favicon is enough for modern browsers.
  head: [['link', { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' }]],

  // Default to light mode for first-time visitors (instead of honoring
  // prefers-color-scheme), but keep the toggle. VitePress merges this
  // object into VueUse's `useDark({...})`, so returning users still see
  // whatever they last picked.
  appearance: { initialValue: 'light' },

  mpa: true,

  // Run the example build before VitePress, so docs/public/examples/* exist.
  // (We expose the same trigger via package.json scripts; VitePress itself
  // doesn't need a hook here.)

  markdown: {
    // Register the .gg TextMate grammar so ```gg fenced blocks get
    // highlighted the same way VitePress highlights any other language.
    // The Example component pulls the same JSON at runtime.
    languages: [ggGrammar as any],
    // ```gg-diagram blocks are rendered to inline SVG at build time via
    // Gridgram's own pipeline. Distinct from ```gg (which stays as a
    // syntax-highlighted code sample).
    config(md) {
      md.use(ggDiagramPlugin);
    },
  },

  themeConfig: {
    logo: "/logo.svg",
    socialLinks: [
      { icon: "github", link: "https://github.com/ideamans/gridgram" },
    ],
  },

  locales: {
    // Root is the language-selector page only — no nav/sidebar.
    root: {
      label: "",
      lang: "en",
    },

    en: {
      label: "English",
      lang: "en",
      link: "/en/",
      themeConfig: {
        nav: [
          { text: "User Guide", link: "/en/guide/" },
          { text: "Developer Guide", link: "/en/developer/" },
          { text: "Gallery", link: "/en/gallery/" },
          { text: "Editor", link: "/en/editor" },
        ],
        sidebar: {
          "/en/guide/": [
            {
              text: "Getting Started",
              items: [
                { text: "Quick start", link: "/en/guide/" },
                { text: "First Gridgram", link: "/en/guide/first-gridgram" },
                { text: "Install", link: "/en/guide/install" },
              ],
            },
            {
              text: "Icon",
              items: [
                { text: "Overview", link: "/en/guide/icon/" },
                { text: "Badge", link: "/en/guide/icon/badge" },
                { text: "Size", link: "/en/guide/icon/size" },
                { text: "Custom", link: "/en/guide/icon/custom" },
              ],
            },
            {
              text: "Connector",
              items: [
                { text: "Overview", link: "/en/guide/connector/" },
                { text: "Labels", link: "/en/guide/connector/labels" },
                { text: "Waypoints", link: "/en/guide/connector/waypoints" },
                { text: "Styles", link: "/en/guide/connector/styles" },
              ],
            },
            {
              text: "Region",
              items: [
                { text: "Overview", link: "/en/guide/region/" },
                { text: "Spanning", link: "/en/guide/region/spanning" },
                { text: "Styling", link: "/en/guide/region/styling" },
              ],
            },
            {
              text: "Note",
              items: [{ text: "Overview", link: "/en/guide/note/" }],
            },
            {
              text: "Color",
              items: [
                { text: "Overview", link: "/en/guide/color/" },
                { text: "Theme", link: "/en/guide/color/theme" },
              ],
            },
            {
              text: "Document",
              items: [
                { text: "Overview", link: "/en/guide/document/" },
                { text: "Grid", link: "/en/guide/document/grid" },
                { text: "Merging", link: "/en/guide/document/merging" },
              ],
            },
            { text: "CLI", link: "/en/guide/cli" },
          ],
          "/en/developer/": [
            {
              text: "Developer Guide",
              items: [
                { text: "Overview", link: "/en/developer/" },
                { text: "Quickstart (TS API)", link: "/en/developer/quickstart" },
              ],
            },
            {
              text: "API Reference",
              items: [
                { text: "renderDiagram & friends", link: "/en/developer/render" },
                { text: "Types", link: "/en/developer/types" },
                { text: "Configuration", link: "/en/developer/config" },
                { text: "Parser", link: "/en/developer/parser" },
                { text: "Diagnostics", link: "/en/developer/diagnostics" },
              ],
            },
            {
              text: "Guides",
              items: [
                { text: "Integrations", link: "/en/developer/integrations" },
                { text: "Specification", link: "/en/developer/spec" },
              ],
            },
          ],
          "/en/gallery/": [
            {
              text: "Gallery",
              items: [
                { text: "Overview", link: "/en/gallery/" },
              ],
            },
            {
              text: "Technology & engineering",
              items: [
                { text: "Infrastructure", link: "/en/gallery/infrastructure" },
                { text: "Microservices", link: "/en/gallery/microservices" },
                { text: "Software architecture", link: "/en/gallery/software-architecture" },
                { text: "Database", link: "/en/gallery/database" },
                { text: "API design", link: "/en/gallery/api-design" },
                { text: "Event-driven", link: "/en/gallery/event-driven" },
                { text: "CI / CD", link: "/en/gallery/ci-cd" },
                { text: "Testing", link: "/en/gallery/testing" },
                { text: "Release & roadmap", link: "/en/gallery/release-roadmap" },
                { text: "Security & auth", link: "/en/gallery/security-auth" },
                { text: "AI / ML", link: "/en/gallery/ai-ml" },
                { text: "Data pipelines", link: "/en/gallery/data-pipelines" },
                { text: "IoT / hardware", link: "/en/gallery/iot-hardware" },
              ],
            },
            {
              text: "Business & people",
              items: [
                { text: "Business workflow", link: "/en/gallery/business-workflow" },
                { text: "Customer journey", link: "/en/gallery/customer-journey" },
                { text: "Org chart", link: "/en/gallery/org-chart" },
                { text: "Project planning", link: "/en/gallery/project-planning" },
                { text: "Sales funnel", link: "/en/gallery/sales-funnel" },
              ],
            },
            {
              text: "Operations & logistics",
              items: [
                { text: "Supply chain", link: "/en/gallery/supply-chain" },
                { text: "Warehouse", link: "/en/gallery/warehouse" },
                { text: "Manufacturing", link: "/en/gallery/manufacturing" },
                { text: "Delivery", link: "/en/gallery/delivery" },
              ],
            },
            {
              text: "Knowledge & communication",
              items: [
                { text: "Education", link: "/en/gallery/education" },
                { text: "Knowledge graph", link: "/en/gallery/knowledge-graph" },
              ],
            },
          ],
        },
        editLink: {
          pattern: "https://github.com/ideamans/gridgram/edit/main/docs/:path",
        },
      },
    },

    ja: {
      label: "日本語",
      lang: "ja",
      link: "/ja/",
      themeConfig: {
        nav: [
          { text: "ガイド", link: "/ja/guide/" },
          { text: "API", link: "/ja/api/" },
          { text: "ギャラリー", link: "/ja/gallery" },
        ],
        sidebar: {
          "/ja/guide/": [
            {
              text: "はじめに",
              items: [
                { text: "Gridgram とは", link: "/ja/guide/" },
                {
                  text: "クイックスタート (.gg)",
                  link: "/ja/guide/quickstart-gg",
                },
              ],
            },
            {
              text: "アイコン",
              items: [
                { text: "概要", link: "/ja/guide/icon/" },
                { text: "バッジ", link: "/ja/guide/icon/badge" },
                { text: "サイズ", link: "/ja/guide/icon/size" },
                { text: "カスタム", link: "/ja/guide/icon/custom" },
              ],
            },
            {
              text: "コネクタ",
              items: [
                { text: "概要", link: "/ja/guide/connector/" },
                { text: "ラベル", link: "/ja/guide/connector/labels" },
                { text: "中継点", link: "/ja/guide/connector/waypoints" },
                { text: "スタイル", link: "/ja/guide/connector/styles" },
              ],
            },
            {
              text: "リージョン",
              items: [
                { text: "概要", link: "/ja/guide/region/" },
                { text: "スパン", link: "/ja/guide/region/spanning" },
                { text: "スタイリング", link: "/ja/guide/region/styling" },
              ],
            },
            {
              text: "ノート",
              items: [{ text: "概要", link: "/ja/guide/note/" }],
            },
            {
              text: "カラー",
              items: [
                { text: "概要", link: "/ja/guide/color/" },
                { text: "テーマ", link: "/ja/guide/color/theme" },
              ],
            },
            {
              text: "ドキュメント",
              items: [
                { text: "概要", link: "/ja/guide/document/" },
                { text: "グリッド", link: "/ja/guide/document/grid" },
                { text: "マージ", link: "/ja/guide/document/merging" },
              ],
            },
            { text: "CLI", link: "/ja/guide/cli" },
            { text: "仕様", link: "/ja/guide/spec" },
          ],
          "/ja/api/": [
            {
              text: "API リファレンス",
              items: [
                { text: "概要", link: "/ja/api/" },
                {
                  text: "クイックスタート (TS API)",
                  link: "/ja/api/quickstart-ts",
                },
                { text: "型", link: "/ja/api/types" },
                { text: "render と build", link: "/ja/api/render" },
                { text: "設定システム", link: "/ja/api/config" },
                { text: "パーサー", link: "/ja/api/parser" },
                { text: "統合レシピ", link: "/ja/api/integrations" },
              ],
            },
          ],
        },
        editLink: {
          pattern: "https://github.com/ideamans/gridgram/edit/main/docs/:path",
          text: "このページを編集",
        },
      },
    },
  },
});
