import { withTheme } from "vitepress-daisyui-theme/config";
import ggGrammar from "./gg.tmLanguage.json";
import { ggDiagramPlugin } from "./plugins/gg-diagram";

/**
 * Three-entry structure:
 *   - /         Language-select landing (neutral; picks /en/ or /ja/)
 *   - /en/…     English docs
 *   - /ja/…     Japanese docs
 *
 * VitePress requires a `root` locale. We use it to host ONLY the top-level
 * language picker at `/index.md`; the English docs live entirely under
 * `/en/*`, matching the `/ja/*` shape.
 */

/**
 * Force light mode, even if a returning visitor's localStorage /
 * prefers-color-scheme asks for dark. `appearance: false` in the config
 * disables VitePress's own toggle, but vitepress-daisyui-theme still
 * injects a FOUC script that sets `data-theme="dark"` based on
 * localStorage / media query. This snippet runs AFTER that script (it's
 * appended to the head array post-withTheme) and overrides both.
 */
const FORCE_LIGHT_SCRIPT = `(()=>{try{localStorage.removeItem('vitepress-theme-appearance');}catch(e){}document.documentElement.dataset.theme='light';document.documentElement.classList.remove('dark');})();`;

// `withTheme` returns a VitePress config with the daisyui FOUC script
// already injected. We capture the result so we can append our own
// force-light script *after* theirs.
const config: ReturnType<typeof withTheme> = withTheme({
  title: "Gridgram",
  description:
    "Diagrams for the AI era. A plain-text DSL that humans, CLIs, and LLMs all author fluently, with byte-deterministic SVG output.",
  cleanUrls: true,
  lastUpdated: true,
  // Phase 1: skeleton pages aren't all written yet — relax until content lands.
  ignoreDeadLinks: true,

  // `favicon.svg` is generated by `scripts/pick-monthly-logo.ts` from
  // `docs/public/icons/logo-NN.svg` (one of 12 variants, picked by the
  // current month). SVG favicon is enough for modern browsers.
  head: [
    ["link", { rel: "icon", type: "image/svg+xml", href: "/favicon.svg" }],
    // ideamans tracking tag — fires on first paint. Subsequent SPA
    // route changes are handled by installRouteTracker() in theme/index.ts,
    // which re-injects the same script on every vue-router navigation.
    [
      "script",
      {
        src: "https://tags.ideamans.com/scripts/gridgram.js",
        async: "",
        "data-gg-tracking": "1",
      },
    ],
  ],

  // Lock to light mode. `appearance: false` disables VitePress's
  // dark-mode machinery entirely (isDark stays false, no prefers-color-
  // scheme watcher, no localStorage persistence). The daisyui theme
  // still renders its ThemeSwitch button in the header, so we hide it
  // via CSS in docs/.vitepress/theme/custom.css.
  appearance: false,

  // Run the example build before VitePress, so docs/public/examples/* exist.
  // (We expose the same trigger via package.json scripts; VitePress itself
  // doesn't need a hook here.)

  markdown: {
    // Register the .gg TextMate grammar so ```gg fenced blocks get
    // highlighted the same way VitePress highlights any other language.
    // The Example component pulls the same JSON at runtime.
    languages: [ggGrammar as any],
    // ```gg-diagram blocks are rendered to inline SVG at build time via
    // Gridgram's own pipeline. Distinct from ```gg (which stays as a
    // syntax-highlighted code sample).
    config(md) {
      md.use(ggDiagramPlugin);
    },
  },

  themeConfig: {
    logo: "/logo.svg",
    search: {
      provider: "local",
      options: {
        locales: {
          ja: {
            translations: {
              button: {
                buttonText: "検索",
                buttonAriaLabel: "検索",
              },
              modal: {
                displayDetails: "詳細を表示",
                resetButtonTitle: "検索をリセット",
                backButtonTitle: "検索を閉じる",
                noResultsText: "結果が見つかりません",
                footer: {
                  selectText: "選択",
                  selectKeyAriaLabel: "enter",
                  navigateText: "移動",
                  navigateUpKeyAriaLabel: "上矢印",
                  navigateDownKeyAriaLabel: "下矢印",
                  closeText: "閉じる",
                  closeKeyAriaLabel: "escape",
                },
              },
            },
          },
        },
      },
    },
    socialLinks: [
      { icon: "github", link: "https://github.com/ideamans/gridgram" },
    ],
    // Site-wide footer. The daisyui theme's Footer.vue reads
    // themeConfig.footer.{message, copyright} and renders both on every
    // layout (Home / Page / Doc). Credit only — no need to translate.
    footer: {
      copyright: "© ideaman's Inc.",
    },
  },

  locales: {
    // Root is the language-selector page only — no nav/sidebar.
    root: {
      label: "",
      lang: "en",
    },

    en: {
      label: "English",
      lang: "en",
      // `link` is intentionally omitted so the LangSwitch preserves the
      // current subpath and just swaps /en/ ↔ /ja/ instead of jumping to
      // the locale root.
      themeConfig: {
        // Logo click within the EN locale returns to /en/ (not the
        // global language-picker at /).
        logoLink: "/en/",
        nav: [
          { text: "User Guide", link: "/en/guide/" },
          { text: "Developer Guide", link: "/en/developer/" },
          { text: "AI Guide", link: "/en/ai/" },
          { text: "Gallery", link: "/en/gallery/" },
          // Editor page exists at /en/editor but is hidden from nav for now.
          // { text: "Editor", link: "/en/editor" },
        ],
        sidebar: {
          "/en/guide/": [
            {
              text: "Getting Started",
              items: [
                { text: "Quick start", link: "/en/guide/" },
                { text: "First Gridgram", link: "/en/guide/first-gridgram" },
                { text: "Install", link: "/en/guide/install" },
              ],
            },
            {
              text: "Icon Node",
              items: [
                { text: "Overview", link: "/en/guide/icon/" },
                { text: "Badge", link: "/en/guide/icon/badge" },
                { text: "Size", link: "/en/guide/icon/size" },
                { text: "Custom", link: "/en/guide/icon/custom" },
              ],
            },
            {
              text: "Connector",
              items: [
                { text: "Overview", link: "/en/guide/connector/" },
                { text: "Labels", link: "/en/guide/connector/labels" },
                { text: "Waypoints", link: "/en/guide/connector/waypoints" },
                { text: "Styles", link: "/en/guide/connector/styles" },
              ],
            },
            {
              text: "Region",
              items: [
                { text: "Overview", link: "/en/guide/region/" },
                { text: "Spanning", link: "/en/guide/region/spanning" },
                { text: "Styling", link: "/en/guide/region/styling" },
              ],
            },
            {
              text: "Note",
              items: [{ text: "Overview", link: "/en/guide/note/" }],
            },
            {
              text: "Frame",
              items: [{ text: "Overview", link: "/en/guide/frame/" }],
            },
            {
              text: "Color",
              items: [
                { text: "Overview", link: "/en/guide/color/" },
                { text: "Theme", link: "/en/guide/color/theme" },
              ],
            },
            {
              text: "Document",
              items: [
                { text: "Overview", link: "/en/guide/document/" },
                { text: "Grid", link: "/en/guide/document/grid" },
                { text: "Merging", link: "/en/guide/document/merging" },
              ],
            },
            { text: "CLI", link: "/en/guide/cli" },
          ],
          "/en/developer/": [
            {
              text: "Developer Guide",
              items: [
                { text: "Overview", link: "/en/developer/" },
                {
                  text: "Quickstart (TS API)",
                  link: "/en/developer/quickstart",
                },
              ],
            },
            {
              text: "API Reference",
              items: [
                {
                  text: "renderDiagram & friends",
                  link: "/en/developer/render",
                },
                { text: "Types", link: "/en/developer/types" },
                { text: "Configuration", link: "/en/developer/config" },
                { text: "Parser", link: "/en/developer/parser" },
                { text: "Diagnostics", link: "/en/developer/diagnostics" },
              ],
            },
            {
              text: "Guides",
              items: [
                { text: "Integrations", link: "/en/developer/integrations" },
                { text: "Specification", link: "/en/developer/spec" },
              ],
            },
          ],
          "/en/ai/": [
            {
              text: "AI Guide",
              items: [
                { text: "Overview", link: "/en/ai/" },
              ],
            },
            {
              text: "Tutorials",
              items: [
                { text: "Claude Code plugin", link: "/en/ai/claude-plugin" },
                { text: "gh skill (Copilot / Cursor / …)", link: "/en/ai/gh-skill" },
                { text: "context7 (MCP retrieval)", link: "/en/ai/context7" },
              ],
            },
            {
              text: "Reference",
              items: [
                { text: "gg llm / gg icons", link: "/en/ai/cli" },
                { text: "llms.txt", link: "/en/ai/llms-txt" },
              ],
            },
          ],
          "/en/gallery/": [
            {
              text: "Gallery",
              items: [{ text: "Overview", link: "/en/gallery/" }],
            },
            {
              text: "Technology & engineering",
              items: [
                { text: "Infrastructure", link: "/en/gallery/infrastructure" },
                { text: "Microservices", link: "/en/gallery/microservices" },
                {
                  text: "Software architecture",
                  link: "/en/gallery/software-architecture",
                },
                { text: "Database", link: "/en/gallery/database" },
                { text: "API design", link: "/en/gallery/api-design" },
                { text: "Event-driven", link: "/en/gallery/event-driven" },
                { text: "CI / CD", link: "/en/gallery/ci-cd" },
                { text: "Testing", link: "/en/gallery/testing" },
                {
                  text: "Release & roadmap",
                  link: "/en/gallery/release-roadmap",
                },
                { text: "Security & auth", link: "/en/gallery/security-auth" },
                { text: "AI / ML", link: "/en/gallery/ai-ml" },
                { text: "Data pipelines", link: "/en/gallery/data-pipelines" },
                { text: "IoT / hardware", link: "/en/gallery/iot-hardware" },
              ],
            },
            {
              text: "Business & people",
              items: [
                {
                  text: "Business workflow",
                  link: "/en/gallery/business-workflow",
                },
                {
                  text: "Customer journey",
                  link: "/en/gallery/customer-journey",
                },
                { text: "Org chart", link: "/en/gallery/org-chart" },
                {
                  text: "Project planning",
                  link: "/en/gallery/project-planning",
                },
                { text: "Sales funnel", link: "/en/gallery/sales-funnel" },
              ],
            },
            {
              text: "Operations & logistics",
              items: [
                { text: "Supply chain", link: "/en/gallery/supply-chain" },
                { text: "Warehouse", link: "/en/gallery/warehouse" },
                { text: "Manufacturing", link: "/en/gallery/manufacturing" },
                { text: "Delivery", link: "/en/gallery/delivery" },
              ],
            },
            {
              text: "Knowledge & communication",
              items: [
                { text: "Education", link: "/en/gallery/education" },
                {
                  text: "Knowledge graph",
                  link: "/en/gallery/knowledge-graph",
                },
              ],
            },
          ],
        },
        editLink: {
          pattern: "https://github.com/ideamans/gridgram/edit/main/docs/:path",
        },
      },
    },

    ja: {
      label: "日本語",
      lang: "ja",
      // `link` omitted — see the /en/ entry for the rationale.
      themeConfig: {
        // Logo click within the JA locale returns to /ja/.
        logoLink: "/ja/",
        nav: [
          { text: "ユーザーガイド", link: "/ja/guide/" },
          { text: "開発者ガイド", link: "/ja/developer/" },
          { text: "AI ガイド", link: "/ja/ai/" },
          { text: "ギャラリー", link: "/ja/gallery/" },
        ],
        sidebar: {
          "/ja/guide/": [
            {
              text: "はじめに",
              items: [
                { text: "クイックスタート", link: "/ja/guide/" },
                { text: "First Gridgram", link: "/ja/guide/first-gridgram" },
                { text: "インストール", link: "/ja/guide/install" },
              ],
            },
            {
              text: "アイコンノード",
              items: [
                { text: "概要", link: "/ja/guide/icon/" },
                { text: "バッジ", link: "/ja/guide/icon/badge" },
                { text: "サイズ", link: "/ja/guide/icon/size" },
                { text: "カスタム", link: "/ja/guide/icon/custom" },
              ],
            },
            {
              text: "コネクタ",
              items: [
                { text: "概要", link: "/ja/guide/connector/" },
                { text: "ラベル", link: "/ja/guide/connector/labels" },
                { text: "中継点", link: "/ja/guide/connector/waypoints" },
                { text: "スタイル", link: "/ja/guide/connector/styles" },
              ],
            },
            {
              text: "リージョン",
              items: [
                { text: "概要", link: "/ja/guide/region/" },
                { text: "スパン", link: "/ja/guide/region/spanning" },
                { text: "スタイリング", link: "/ja/guide/region/styling" },
              ],
            },
            {
              text: "ノート",
              items: [{ text: "概要", link: "/ja/guide/note/" }],
            },
            {
              text: "フレーム",
              items: [{ text: "概要", link: "/ja/guide/frame/" }],
            },
            {
              text: "カラー",
              items: [
                { text: "概要", link: "/ja/guide/color/" },
                { text: "テーマ", link: "/ja/guide/color/theme" },
              ],
            },
            {
              text: "ドキュメント",
              items: [
                { text: "概要", link: "/ja/guide/document/" },
                { text: "グリッド", link: "/ja/guide/document/grid" },
                { text: "マージ", link: "/ja/guide/document/merging" },
              ],
            },
            { text: "CLI", link: "/ja/guide/cli" },
          ],
          "/ja/developer/": [
            {
              text: "開発者ガイド",
              items: [
                { text: "概要", link: "/ja/developer/" },
                {
                  text: "クイックスタート (TS API)",
                  link: "/ja/developer/quickstart",
                },
              ],
            },
            {
              text: "API リファレンス",
              items: [
                {
                  text: "renderDiagram とその仲間",
                  link: "/ja/developer/render",
                },
                { text: "型", link: "/ja/developer/types" },
                { text: "設定", link: "/ja/developer/config" },
                { text: "パーサー", link: "/ja/developer/parser" },
                { text: "診断", link: "/ja/developer/diagnostics" },
              ],
            },
            {
              text: "ガイド",
              items: [
                { text: "統合レシピ", link: "/ja/developer/integrations" },
                { text: "仕様", link: "/ja/developer/spec" },
              ],
            },
          ],
          "/ja/ai/": [
            {
              text: "AI ガイド",
              items: [
                { text: "概要", link: "/ja/ai/" },
              ],
            },
            {
              text: "チュートリアル",
              items: [
                { text: "Claude Code プラグイン", link: "/ja/ai/claude-plugin" },
                { text: "gh skill (Copilot / Cursor / …)", link: "/ja/ai/gh-skill" },
                { text: "context7 (MCP 取得)", link: "/ja/ai/context7" },
              ],
            },
            {
              text: "リファレンス",
              items: [
                { text: "gg llm / gg icons", link: "/ja/ai/cli" },
                { text: "llms.txt", link: "/ja/ai/llms-txt" },
              ],
            },
          ],
          "/ja/gallery/": [
            {
              text: "ギャラリー",
              items: [{ text: "概要", link: "/ja/gallery/" }],
            },
            {
              text: "テクノロジー & エンジニアリング",
              items: [
                { text: "インフラ", link: "/ja/gallery/infrastructure" },
                { text: "マイクロサービス", link: "/ja/gallery/microservices" },
                {
                  text: "ソフトウェアアーキテクチャ",
                  link: "/ja/gallery/software-architecture",
                },
                { text: "データベース", link: "/ja/gallery/database" },
                { text: "API 設計", link: "/ja/gallery/api-design" },
                { text: "イベント駆動", link: "/ja/gallery/event-driven" },
                { text: "CI / CD", link: "/ja/gallery/ci-cd" },
                { text: "テスト", link: "/ja/gallery/testing" },
                {
                  text: "リリース & ロードマップ",
                  link: "/ja/gallery/release-roadmap",
                },
                {
                  text: "セキュリティ & 認証",
                  link: "/ja/gallery/security-auth",
                },
                { text: "AI / ML", link: "/ja/gallery/ai-ml" },
                {
                  text: "データパイプライン",
                  link: "/ja/gallery/data-pipelines",
                },
                {
                  text: "IoT / ハードウェア",
                  link: "/ja/gallery/iot-hardware",
                },
              ],
            },
            {
              text: "ビジネス & ピープル",
              items: [
                { text: "業務フロー", link: "/ja/gallery/business-workflow" },
                {
                  text: "カスタマージャーニー",
                  link: "/ja/gallery/customer-journey",
                },
                { text: "組織図", link: "/ja/gallery/org-chart" },
                {
                  text: "プロジェクト計画",
                  link: "/ja/gallery/project-planning",
                },
                { text: "セールスファネル", link: "/ja/gallery/sales-funnel" },
              ],
            },
            {
              text: "オペレーション & ロジスティクス",
              items: [
                { text: "サプライチェーン", link: "/ja/gallery/supply-chain" },
                { text: "倉庫", link: "/ja/gallery/warehouse" },
                { text: "製造", link: "/ja/gallery/manufacturing" },
                { text: "配送", link: "/ja/gallery/delivery" },
              ],
            },
            {
              text: "ナレッジ & コミュニケーション",
              items: [
                { text: "教育", link: "/ja/gallery/education" },
                { text: "ナレッジグラフ", link: "/ja/gallery/knowledge-graph" },
              ],
            },
          ],
        },
        editLink: {
          pattern: "https://github.com/ideamans/gridgram/edit/main/docs/:path",
          text: "このページを編集",
        },
      },
    },
  },
});

// Append the force-light script AFTER withTheme's FOUC block so it
// runs last in document.head and wins.
config.head = [
  ...(config.head ?? []),
  ["script", { id: "gg-force-light" }, FORCE_LIGHT_SCRIPT],
];

export default config;
